packages:
  - .

allowBuilds:
  canvas: true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - "@ai-sdk/gateway@4.0.0"
  - "@ai-sdk/mcp@2.0.0"
  - "@ai-sdk/openai@4.0.0"
  - "@ai-sdk/provider-utils@5.0.0"
  - "@ai-sdk/provider@4.0.0"
  - "@ai-sdk/react@4.0.0"
  - ai@7.0.0
  - "@ai-sdk/openai-compatible@3.0.0"
  - "@astrojs/telemetry@3.3.3"
  - astro@7.0.7 || 7.2.3
  - '@astrojs/internal-helpers@0.10.3'
  - '@astrojs/markdown-remark@7.2.3'
  - '@astrojs/markdown-satteri@0.3.6'
  - '@astrojs/mdx@7.0.6'
  - '@astrojs/react@6.0.3'
