export const newsSourceLogos: Record<string, string> = {
	UDN: "/news-logos/udn.png",
	聯合報: "/news-logos/udn.png",
	自由時報: "/news-logos/ltn.png",
	中央社: "/news-logos/cna.png",
	"Focus Taiwan - CNA English News": "/news-logos/cna.png",
	"ETtoday 新聞雲": "/news-logos/ettoday.png",
	今日新聞: "/news-logos/nownews.png",
	中時新聞網: "/news-logos/chinatimes.png",
	梅花新聞網: "/news-logos/i-meihua.png",
	三立新聞: "/news-logos/setn.png",
	壹蘋新聞網: "/news-logos/nextapple.png",
	風傳媒: "/news-logos/storm.png",
	動區動趨: "/news-logos/blocktempo.png",
	中央廣播電臺: "/news-logos/rti.png",
	信傳媒: "/news-logos/cmmedia.png",
	公視新聞網: "/news-logos/pts.ico",
	TVBS新聞網: "/news-logos/tvbs.png",
	匯流新聞網: "/news-logos/cnews.png",
	經濟日報: "/news-logos/economic-daily.png",
	CTWANT: "/news-logos/ctwant.png",
	太報: "/news-logos/taisounds.png",
	民視新聞網: "/news-logos/ftvnews.png",
	知新聞: "/news-logos/knews.png",
	人間福報: "/news-logos/merit-times.png",
	華視新聞網: "/news-logos/cts.png",
	"Domino Theory": "/news-logos/domino-theory.png",
	"BigGo Finance": "/news-logos/biggo-finance.png",
	"Bloomberg Law": "/news-logos/bloomberg-law.png",
	"BTC Times": "/news-logos/btctimes.png",
	CoinDesk: "/news-logos/coindesk.png",
	ICRT: "/news-logos/icrt.png",
	"Taiwan News": "/news-logos/taiwan-news.png",
	"Yahoo Finance": "/news-logos/yahoo-finance.png",
	"Yahoo News": "/news-logos/yahoo-news.png",
	中天新聞網: "/news-logos/ctinews.png",
	元豐媒體: "/news-logos/yuanfengmedia.png",
	"爆新聞 Bow Media": "/news-logos/bowmedia.png",
	"鏡週刊 Mirror Media": "/news-logos/mirrormedia.png",
};

export function getNewsSourceLogo(source?: string | null) {
	if (!source) return null;
	return newsSourceLogos[source.trim()] ?? null;
}
