name: Auto Sync Docs to Supabase with Vectorization

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Check changed-files
    steps:
      - uses: actions/checkout@v4
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45
        with:
          files: |
            **.mdx

      - name: Setup Node.js
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        run: pnpm install

      - name: Sync Changed Markdown to Supabase
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            node utils/sync-docs-supabase-vector.mjs "$file"
            echo "$file was changed"
          done
